# Generated by Django 3.2.8 on 2022-11-24 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myusers',
            name='email',
            field=models.EmailField(blank=True, max_length=254, unique=True),
        ),
    ]
