# Generated by Django 3.2.8 on 2022-11-15 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='data_create',
            field=models.DateField(auto_now_add=True),
        ),
    ]
